### ISSUE TITLE
Redo docstrings checklist.

### ISSUE THREAD

**Issue by coledie** [SpikeyCNS/spikey#1]
Format
--------
```python
"""
Short description

Parameters
------------
param: type
    Description of variable
...

Returns
---------
type Description of return

Usage
-------
```python
...
\```
"""
```
If is an ndarray, use ndarray[dim1, dim2](dtype if applicable).
- Not much of existing documentation is this specific but should be moving forward.

Top of file docstring be copy of most relevant object docstring.

Doc Checklist (All in one PR)
----------
- [x] Setup.py description outdated.
- [x] Setup.py version "DEVELOPMENT" overwritten in main, remove but test install after.
- [x] core/
- [x] experiments/
- [x] games/RL/
- [x] games/MetaRL/
- [x] logging/
- [x] viz/
- [x] meta/
- [x] snn/input
- [x] snn/modifier
- [x] snn/neuron
- [x] snn/readout
- [x] snn/reward
- [x] snn/synapse
- [x] snn/weight - Note matrix must be ma.
- [x] snn/network - Clear there is multiple network options.
- [x] Link to relevant sections of readme in callback, trainingloop, logger, reader, ...
- [x] np.ndarray type hints -> specific ndarray dtypes

Type Hint Checklist (All in one PR)
----------
- [x] core/
- [x] experiments/
- [x] games/RL/
- [x] games/MetaRL/
- [x] logging/
- [x] viz/
- [x] meta/
- [x] snn/input
- [x] snn/modifier
- [x] snn/neuron
- [x] snn/readout
- [x] snn/reward
- [x] snn/synapse
- [x] snn/weight - Note matrix must be ma.
- [x] snn/network - Clear there is multiple network options.
