### ISSUE TITLE
Improve testing checklist.

### ISSUE THREAD

**Issue by coledie** [SpikeyCNS/spikey#2]
- [x] Delete pytest requirements(add gym), delete test.conf, update test running docs, remove all NBVAL usage
- [x] Base all tests off custom base class w/ runall functionality - one for modules, one general
- [x] Figure how to make individual implementations support custom testing, eg one base test, each template and selectively super() then append
- [x] Module testing template test each and every module subclass on each base module fn
- [x] All different input schemes from metapath dir skip.
- [x] Ensure all modules pickleable(add to base class and default runall)
- [x] Network - Test different initializations and override orders
- [x] Inputs
- [x] Modifier
- [x] Neuron
- [x] Readout
- [x] Reward
- [x] Synapse
- [x] Weight
- [x] Game(test gym) - Test different initializations and override orders
- [x] RL
- [x] MetaRL
- [x] TrainingLoop - Test different callback passing in methods
- [x] Callback
- [x] Logger, MultiLogger
- [x] Reader, MetaReader - breaks on bool arrays, empty and single item lists
- [x] Sanitize
- [x] Serialize
- [x] Backends
- [x] Series(Mock backend)
- [x] Population(Mock backend)
- [x] GenotypeCache
- [x] CI pipeline w/ 3.7, 3.8 linux - run on merge.
- [x] Make tests a PR requirement.
